version: '2'
services:
  frontend:
    build:
      context: . 
      args: 
        - "-t madhums"
    container_name: frontend.jm.lan
    command: npm start
    depends_on:
      - mongodb
    ports:
      - 80:3000
    links:
      - mongodb
    networks:
      default:
        aliases:
          - nodedemo-network
    env_file:
      - .env
    environment:
      - MONGOHQ_URL=mongodb://mongo.jm.lan/nodedemo_prod
  mongodb:
    container_name: mongo.jm.lan
    image: mongo:latest
    command: --smallfiles
    ports:
      - 27017:27017
    networks:
      default:
        aliases:
          - nodedemo-network
networks:
  default:
    external: 
      name: nodedemo-network