version: '3'
services:
  frontend:
  # we use local registry for testing https://linuxconfig.org/how-to-run-your-own-local-private-docker-registry
    image: localhost:5000/nemd:1
    command: npm start
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - MONGOHQ_URL=mongodb://mongodb/nodedemo_prod
      - BASEURL=http://localhost
      - SERVICE_PORTS=3000
      - NODE_ENV=production
    networks: 
      - nemnetwork
    deploy:
      replicas: 3
      update_config: 
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
# using proxy as in https://medium.com/@nirgn/load-balancing-applications-with-haproxy-and-docker-d719b7c5b231
  proxy:
    image: dockercloud/haproxy:latest
    depends_on:
      - frontend
    environment:
      - BALANCE=roundrobin
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nemnetwork
    links:
      - frontend
    deploy:
      placement:
        constraints: [node.role == manager]
  mongodb:
    image: mongo:latest
    command: --smallfiles
    ports:
      - 27017:27017
    networks:
      - nemnetwork
networks:
  nemnetwork:
    driver: overlay