apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: proxy
    spec:
      containers:
      - env:
        - name: BALANCE
          value: roundrobin
        image: dockercloud/haproxy:latest
        name: proxy
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: proxy-claim0
      restartPolicy: Always
      volumes:
      - name: proxy-claim0
        persistentVolumeClaim:
          claimName: proxy-claim0
status: {}
